bootstrap.servers: 127.0.0.1:9092
sasl.mechanism: SCRAM-SHA-512
security.protocol: SASL_SSL
ssl.truststore.location:
kafka.username: user
kafka.password: pass
kafka.topic: mytopic
kafka.consumer.group: m2
auto.offset.reset: earliest
